### ISSUE TITLE
Counter inc() is messing between labels values and names

### ISSUE THREAD

**Issue by blesenechal** [tweedegolf/prometheus-client#1]
Hi, 

There is an issue in the `inc` method of `TweedeGolf\PrometheusClient\Collector\Counter`, it replaces the labels values by thieir name.

The 4th argument to `$this->storage->incValue()` should be `$labelValues` not `$this->labelNames`

Current code:
```
public function inc($v = 1, array $labelValues = [])
{
    if ($v < 0) {
        throw new PrometheusException("Increment must be positive");
    }
    Validator::validateLabelValues($labelValues, $this->labelNames);
    $this->storage->incValue($this->name, $v, is_int($v) ? 0 : 0.0, $this->labelNames);

    return $this;
}
```

**Comment by er1z** [comment]
My PR contains fix on this issue, feel free to use until this one is being merged.
